//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 12:26:22 PM CLST 
//


package rtl.sod.corp.sche.whmg.appointment.domain.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AppointmentReqMessageAppointmentTpCompanyId_QNAME = new QName("", "Tp_Company_Id");
    private final static QName _AppointmentReqMessageAppointmentCommunicationMode_QNAME = new QName("", "Communication_Mode");
    private final static QName _AppointmentReqMessageAppointmentApptReasonId_QNAME = new QName("", "Appt_Reason_Id");
    private final static QName _AppointmentReqMessageAppointmentCancelledTcApptId_QNAME = new QName("", "Cancelled_Tc_Appt_Id");
    private final static QName _AppointmentReqMessageAppointmentCancelReasonCode_QNAME = new QName("", "Cancel_Reason_code");
    private final static QName _AppointmentReqMessageAppointmentLoadConfiguration_QNAME = new QName("", "Load_Configuration");
    private final static QName _AppointmentReqMessageAppointmentEquipmentCode_QNAME = new QName("", "Equipment_Code");
    private final static QName _AppointmentReqMessageAppointmentDockId_QNAME = new QName("", "Dock_Id");
    private final static QName _AppointmentReqMessageAppointmentReservedApptId_QNAME = new QName("", "Reserved_appt_id");
    private final static QName _AppointmentReqMessageAppointmentApptReasonCode_QNAME = new QName("", "Appt_Reason_Code");
    private final static QName _AppointmentReqMessageAppointmentEquipmentID_QNAME = new QName("", "Equipment_ID");
    private final static QName _AppointmentReqMessageAppointmentLoadUnloadStartDttm_QNAME = new QName("", "Load_Unload_Start_Dttm");
    private final static QName _AppointmentReqMessageAppointmentCancelIndicator_QNAME = new QName("", "Cancel_Indicator");
    private final static QName _AppointmentReqMessageAppointmentTemplateId_QNAME = new QName("", "template_Id");
    private final static QName _AppointmentReqMessageAppointmentScheduledDttm_QNAME = new QName("", "Scheduled_Dttm");
    private final static QName _AppointmentReqMessageAppointmentTrailerDurationInMin_QNAME = new QName("", "Trailer_Duration_In_Min");
    private final static QName _AppointmentReqMessageAppointmentAppointmentID_QNAME = new QName("", "Appointment_ID");
    private final static QName _AppointmentReqMessageAppointmentLoadUnloadEndDttm_QNAME = new QName("", "Load_Unload_End_Dttm");
    private final static QName _AppointmentReqMessageAppointmentAppointmentStatus_QNAME = new QName("", "Appointment_Status");
    private final static QName _AppointmentReqMessageAppointmentRequestorName_QNAME = new QName("", "Requestor_name");
    private final static QName _AppointmentReqMessageAppointmentAppointmentComments_QNAME = new QName("", "Appointment_Comments");
    private final static QName _AppointmentReqMessageAppointmentDoorId_QNAME = new QName("", "Door_Id");
    private final static QName _AppointmentReqMessageAppointmentDriverID_QNAME = new QName("", "Driver_ID");
    private final static QName _AppointmentReqMessageAppointmentBusinessPartner_QNAME = new QName("", "Business_partner");
    private final static QName _AppointmentReqMessageAppointmentSealNumber_QNAME = new QName("", "Seal_Number");
    private final static QName _AppointmentReqMessageAppointmentTractorType_QNAME = new QName("", "Tractor_Type");
    private final static QName _AppointmentReqMessageAppointmentControlNumber_QNAME = new QName("", "Control_number");
    private final static QName _AppointmentReqMessageAppointmentTractorID_QNAME = new QName("", "Tractor_ID");
    private final static QName _AppointmentReqMessageAppointmentCarrierCode_QNAME = new QName("", "Carrier_Code");
    private final static QName _AppointmentReqMessageAppointmentEquipment_QNAME = new QName("", "Equipment");
    private final static QName _AppointmentReqMessageAppointmentAppointmentPriority_QNAME = new QName("", "Appointment_priority");
    private final static QName _AppointmentReqMessageAppointmentDriverDurationInMin_QNAME = new QName("", "Driver_Duration_In_Min");
    private final static QName _AppointmentReqMessageAppointmentCheckOutDttm_QNAME = new QName("", "Check_Out_Dttm");
    private final static QName _AppointmentReqMessageAppointmentAppointmentSource_QNAME = new QName("", "Appointment_Source");
    private final static QName _AppointmentReqMessageAppointmentActualCheckInDttm_QNAME = new QName("", "Actual_CheckIn_Dttm");
    private final static QName _AppointmentReqMessageAppointmentBusinessUnit_QNAME = new QName("", "Business_Unit");
    private final static QName _AppointmentReqMessageAppointmentRequestorType_QNAME = new QName("", "Requestor_type");
    private final static QName _AppointmentReqMessageAppointmentLoadPosition_QNAME = new QName("", "Load_position");
    private final static QName _AppointmentReqMessageAppointmentCustomAttributeAttributeName_QNAME = new QName("", "Attribute_Name");
    private final static QName _AppointmentReqMessageAppointmentCustomAttributeAttributeValue_QNAME = new QName("", "Attribute_Value");
    private final static QName _AppointmentReqMessageAppointmentApptObjectObjectType_QNAME = new QName("", "Object_Type");
    private final static QName _AppointmentReqMessageAppointmentApptObjectObjectID_QNAME = new QName("", "Object_ID");
    private final static QName _AppointmentReqMessageAppointmentApptObjectStopSeq_QNAME = new QName("", "Stop_Seq");
    private final static QName _AppointmentReqMessageAppointmentAppointmentSlotsSlotDuration_QNAME = new QName("", "Slot_Duration");
    private final static QName _AppointmentReqMessageAppointmentAppointmentSlotsCapacityUsed_QNAME = new QName("", "Capacity_Used");
    private final static QName _AppointmentReqMessageAppointmentAppointmentSlotsSlotId_QNAME = new QName("", "Slot_Id");
    private final static QName _AppointmentReqMessageAppointmentAppointmentSlotsSlotStartDttm_QNAME = new QName("", "Slot_Start_Dttm");
    private final static QName _AppointmentReqMessageAppointmentApptObjectPurchaseOrderTCOrderId_QNAME = new QName("", "TC_Order_Id");
    private final static QName _AppointmentReqMessageAppointmentApptObjectPurchaseOrderBookedSize_QNAME = new QName("", "Booked_Size");
    private final static QName _AppointmentReqMessageAppointmentApptObjectPurchaseOrderSizeUOM_QNAME = new QName("", "Size_UOM");
    private final static QName _AppointmentReqHeaderMsgLocale_QNAME = new QName("", "Msg_Locale");
    private final static QName _AppointmentReqHeaderMsgTimeZone_QNAME = new QName("", "Msg_Time_Zone");
    private final static QName _AppointmentReqHeaderSendMessage_QNAME = new QName("", "Send_Message");
    private final static QName _AppointmentReqHeaderVersion_QNAME = new QName("", "Version");
    private final static QName _AppointmentReqHeaderReferenceID_QNAME = new QName("", "Reference_ID");
    private final static QName _AppointmentReqHeaderSequenceNumber_QNAME = new QName("", "Sequence_Number");
    private final static QName _AppointmentReqHeaderSequence_QNAME = new QName("", "Sequence");
    private final static QName _AppointmentReqHeaderUserID_QNAME = new QName("", "User_ID");
    private final static QName _AppointmentReqHeaderCarrierCompany_QNAME = new QName("", "Carrier_Company");
    private final static QName _AppointmentReqHeaderBatchID_QNAME = new QName("", "Batch_ID");
    private final static QName _AppointmentReqHeaderPassword_QNAME = new QName("", "Password");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AppointmentReq }
     * 
     */
    public AppointmentReq createAppointmentReq() {
        return new AppointmentReq();
    }

    /**
     * Create an instance of {@link AppointmentReq.Message }
     * 
     */
    public AppointmentReq.Message createAppointmentReqMessage() {
        return new AppointmentReq.Message();
    }

    /**
     * Create an instance of {@link AppointmentReq.Message.Appointment }
     * 
     */
    public AppointmentReq.Message.Appointment createAppointmentReqMessageAppointment() {
        return new AppointmentReq.Message.Appointment();
    }

    /**
     * Create an instance of {@link AppointmentReq.Message.Appointment.ApptObject }
     * 
     */
    public AppointmentReq.Message.Appointment.ApptObject createAppointmentReqMessageAppointmentApptObject() {
        return new AppointmentReq.Message.Appointment.ApptObject();
    }

    /**
     * Create an instance of {@link AppointmentReq.ClientService }
     * 
     */
    public AppointmentReq.ClientService createAppointmentReqClientService() {
        return new AppointmentReq.ClientService();
    }

    /**
     * Create an instance of {@link AppointmentReq.Header }
     * 
     */
    public AppointmentReq.Header createAppointmentReqHeader() {
        return new AppointmentReq.Header();
    }

    /**
     * Create an instance of {@link AppointmentReq.Message.Appointment.AppointmentSlots }
     * 
     */
    public AppointmentReq.Message.Appointment.AppointmentSlots createAppointmentReqMessageAppointmentAppointmentSlots() {
        return new AppointmentReq.Message.Appointment.AppointmentSlots();
    }

    /**
     * Create an instance of {@link AppointmentReq.Message.Appointment.CustomAttribute }
     * 
     */
    public AppointmentReq.Message.Appointment.CustomAttribute createAppointmentReqMessageAppointmentCustomAttribute() {
        return new AppointmentReq.Message.Appointment.CustomAttribute();
    }

    /**
     * Create an instance of {@link AppointmentReq.Message.Appointment.ApptObject.PurchaseOrder }
     * 
     */
    public AppointmentReq.Message.Appointment.ApptObject.PurchaseOrder createAppointmentReqMessageAppointmentApptObjectPurchaseOrder() {
        return new AppointmentReq.Message.Appointment.ApptObject.PurchaseOrder();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tp_Company_Id", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentTpCompanyId(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentTpCompanyId_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Communication_Mode", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentCommunicationMode(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentCommunicationMode_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Appt_Reason_Id", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentApptReasonId(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentApptReasonId_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cancelled_Tc_Appt_Id", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentCancelledTcApptId(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentCancelledTcApptId_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cancel_Reason_code", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentCancelReasonCode(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentCancelReasonCode_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Load_Configuration", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentLoadConfiguration(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentLoadConfiguration_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Equipment_Code", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentEquipmentCode(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentEquipmentCode_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Dock_Id", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentDockId(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentDockId_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reserved_appt_id", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentReservedApptId(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentReservedApptId_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Appt_Reason_Code", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentApptReasonCode(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentApptReasonCode_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Equipment_ID", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentEquipmentID(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentEquipmentID_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Load_Unload_Start_Dttm", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentLoadUnloadStartDttm(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentLoadUnloadStartDttm_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cancel_Indicator", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentCancelIndicator(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentCancelIndicator_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "template_Id", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentTemplateId(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentTemplateId_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Scheduled_Dttm", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentScheduledDttm(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentScheduledDttm_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Trailer_Duration_In_Min", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentTrailerDurationInMin(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentTrailerDurationInMin_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Appointment_ID", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentAppointmentID(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentAppointmentID_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Load_Unload_End_Dttm", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentLoadUnloadEndDttm(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentLoadUnloadEndDttm_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Appointment_Status", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentAppointmentStatus(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentAppointmentStatus_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Requestor_name", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentRequestorName(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentRequestorName_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Appointment_Comments", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentAppointmentComments(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentAppointmentComments_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Door_Id", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentDoorId(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentDoorId_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Driver_ID", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentDriverID(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentDriverID_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Business_partner", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentBusinessPartner(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentBusinessPartner_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Seal_Number", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentSealNumber(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentSealNumber_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tractor_Type", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentTractorType(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentTractorType_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Control_number", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentControlNumber(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentControlNumber_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tractor_ID", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentTractorID(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentTractorID_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Carrier_Code", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentCarrierCode(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentCarrierCode_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Equipment", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentEquipment(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentEquipment_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Appointment_priority", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentAppointmentPriority(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentAppointmentPriority_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Driver_Duration_In_Min", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentDriverDurationInMin(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentDriverDurationInMin_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Check_Out_Dttm", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentCheckOutDttm(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentCheckOutDttm_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Appointment_Source", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentAppointmentSource(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentAppointmentSource_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Actual_CheckIn_Dttm", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentActualCheckInDttm(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentActualCheckInDttm_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Business_Unit", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentBusinessUnit(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentBusinessUnit_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Requestor_type", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentRequestorType(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentRequestorType_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Load_position", scope = AppointmentReq.Message.Appointment.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentLoadPosition(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentLoadPosition_QNAME, String.class, AppointmentReq.Message.Appointment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Attribute_Name", scope = AppointmentReq.Message.Appointment.CustomAttribute.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentCustomAttributeAttributeName(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentCustomAttributeAttributeName_QNAME, String.class, AppointmentReq.Message.Appointment.CustomAttribute.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Attribute_Value", scope = AppointmentReq.Message.Appointment.CustomAttribute.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentCustomAttributeAttributeValue(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentCustomAttributeAttributeValue_QNAME, String.class, AppointmentReq.Message.Appointment.CustomAttribute.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Object_Type", scope = AppointmentReq.Message.Appointment.ApptObject.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentApptObjectObjectType(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentApptObjectObjectType_QNAME, String.class, AppointmentReq.Message.Appointment.ApptObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Object_ID", scope = AppointmentReq.Message.Appointment.ApptObject.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentApptObjectObjectID(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentApptObjectObjectID_QNAME, String.class, AppointmentReq.Message.Appointment.ApptObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Stop_Seq", scope = AppointmentReq.Message.Appointment.ApptObject.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentApptObjectStopSeq(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentApptObjectStopSeq_QNAME, String.class, AppointmentReq.Message.Appointment.ApptObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Slot_Duration", scope = AppointmentReq.Message.Appointment.AppointmentSlots.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentAppointmentSlotsSlotDuration(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentAppointmentSlotsSlotDuration_QNAME, String.class, AppointmentReq.Message.Appointment.AppointmentSlots.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Capacity_Used", scope = AppointmentReq.Message.Appointment.AppointmentSlots.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentAppointmentSlotsCapacityUsed(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentAppointmentSlotsCapacityUsed_QNAME, String.class, AppointmentReq.Message.Appointment.AppointmentSlots.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Slot_Id", scope = AppointmentReq.Message.Appointment.AppointmentSlots.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentAppointmentSlotsSlotId(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentAppointmentSlotsSlotId_QNAME, String.class, AppointmentReq.Message.Appointment.AppointmentSlots.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Slot_Start_Dttm", scope = AppointmentReq.Message.Appointment.AppointmentSlots.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentAppointmentSlotsSlotStartDttm(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentAppointmentSlotsSlotStartDttm_QNAME, String.class, AppointmentReq.Message.Appointment.AppointmentSlots.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TC_Order_Id", scope = AppointmentReq.Message.Appointment.ApptObject.PurchaseOrder.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentApptObjectPurchaseOrderTCOrderId(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentApptObjectPurchaseOrderTCOrderId_QNAME, String.class, AppointmentReq.Message.Appointment.ApptObject.PurchaseOrder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Booked_Size", scope = AppointmentReq.Message.Appointment.ApptObject.PurchaseOrder.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentApptObjectPurchaseOrderBookedSize(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentApptObjectPurchaseOrderBookedSize_QNAME, String.class, AppointmentReq.Message.Appointment.ApptObject.PurchaseOrder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Size_UOM", scope = AppointmentReq.Message.Appointment.ApptObject.PurchaseOrder.class)
    public JAXBElement<String> createAppointmentReqMessageAppointmentApptObjectPurchaseOrderSizeUOM(String value) {
        return new JAXBElement<String>(_AppointmentReqMessageAppointmentApptObjectPurchaseOrderSizeUOM_QNAME, String.class, AppointmentReq.Message.Appointment.ApptObject.PurchaseOrder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Msg_Locale", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderMsgLocale(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderMsgLocale_QNAME, String.class, AppointmentReq.Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Msg_Time_Zone", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderMsgTimeZone(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderMsgTimeZone_QNAME, String.class, AppointmentReq.Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Send_Message", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderSendMessage(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderSendMessage_QNAME, String.class, AppointmentReq.Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderVersion(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderVersion_QNAME, String.class, AppointmentReq.Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reference_ID", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderReferenceID(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderReferenceID_QNAME, String.class, AppointmentReq.Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sequence_Number", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderSequenceNumber(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderSequenceNumber_QNAME, String.class, AppointmentReq.Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sequence", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderSequence(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderSequence_QNAME, String.class, AppointmentReq.Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "User_ID", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderUserID(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderUserID_QNAME, String.class, AppointmentReq.Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Carrier_Company", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderCarrierCompany(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderCarrierCompany_QNAME, String.class, AppointmentReq.Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Batch_ID", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderBatchID(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderBatchID_QNAME, String.class, AppointmentReq.Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Password", scope = AppointmentReq.Header.class)
    public JAXBElement<String> createAppointmentReqHeaderPassword(String value) {
        return new JAXBElement<String>(_AppointmentReqHeaderPassword_QNAME, String.class, AppointmentReq.Header.class, value);
    }

}