<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns1="http://mdwcorp.falabella.com/common/schema/clientservice" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://mdwcorp.falabella.com/SOD/CORP/WLS/schema/Uxpos/Cliente/Documentos/Emitir/Req/v2018.02" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:tns="http://mdwcorp.falabella.com/SOD/CORP/WLS/schema/Uxpos/Cliente/Documentos/Emitir/Request/v2018.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns1 ns0 tns oraxsl"
   >
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="WLS_SOD_CORP_Uxpos_Cliente_Documentos_EmitirReq.xsd"/>
            <oracle-xsl-mapper:rootElement name="ClienteDocumentosEmitirExpReq" namespace="http://mdwcorp.falabella.com/SOD/CORP/WLS/schema/Uxpos/Cliente/Documentos/Emitir/Req/v2018.02"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="MdwCorp_Common_clientService.xsd"/>
            <oracle-xsl-mapper:rootElement name="ClientService" namespace="http://mdwcorp.falabella.com/common/schema/clientservice"/>
            <oracle-xsl-mapper:param name="clientService"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="ClienteDocumentoEmitirRequest.xsd"/>
            <oracle-xsl-mapper:rootElement name="ClienteDocumentosEmitirRequest" namespace="http://mdwcorp.falabella.com/SOD/CORP/WLS/schema/Uxpos/Cliente/Documentos/Emitir/Request/v2018.02"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON FEB 12 22:35:30 CLT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="clientService" />
   <xsl:template match="/">
      <tns:ClienteDocumentosEmitirRequest>
         <tns:HeaderProducer>
            <tns:ClientService>
               <tns:country>
                  <xsl:value-of select="$clientService/ns1:ClientService/ns1:country"/>
               </tns:country>
               <tns:commerce>
                  <xsl:value-of select="$clientService/ns1:ClientService/ns1:commerce"/>
               </tns:commerce>
               <tns:channel>
                  <xsl:value-of select="$clientService/ns1:ClientService/ns1:channel"/>
               </tns:channel>
               <xsl:if test="$clientService/ns1:ClientService/ns1:storeId">
                  <tns:storeId>
                     <xsl:value-of select="$clientService/ns1:ClientService/ns1:storeId"/>
                  </tns:storeId>
               </xsl:if>
               <xsl:if test="$clientService/ns1:ClientService/ns1:terminalId">
                  <tns:terminalId>
                     <xsl:value-of select="$clientService/ns1:ClientService/ns1:terminalId"/>
                  </tns:terminalId>
               </xsl:if>
               <xsl:if test="$clientService/ns1:ClientService/ns1:date">
                  <tns:date>
                     <xsl:value-of select="$clientService/ns1:ClientService/ns1:date"/>
                  </tns:date>
               </xsl:if>
               <xsl:if test="$clientService/ns1:ClientService/ns1:hour">
                  <tns:hour>
                     <xsl:value-of select="$clientService/ns1:ClientService/ns1:hour"/>
                  </tns:hour>
               </xsl:if>
            </tns:ClientService>
         </tns:HeaderProducer>
         <tns:BodyProducer>
            <tns:ClienteDocumentosEmitirProdReq>
               <tns:cabecera>
                  <tns:tipoAccion>
                     <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:tipoAccion"/>
                  </tns:tipoAccion>
                  <tns:idSolicitudVE>
                     <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:idSolicitudVE"/>
                  </tns:idSolicitudVE>
                  <tns:pais>
                     <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:pais"/>
                  </tns:pais>
                  <tns:sucursal>
                     <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:sucursal"/>
                  </tns:sucursal>
                  <tns:orden>
                     <tns:ordenVenta>
                        <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:ordenVenta"/>
                     </tns:ordenVenta>
                     <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:codigoVendedor">
                        <tns:codigoVendedor>
                           <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:codigoVendedor"/>
                        </tns:codigoVendedor>
                     </xsl:if>
                     <tns:tipoDocumentoVenta>
                        <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:tipoDocumentoVenta"/>
                     </tns:tipoDocumentoVenta>
                     <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:numeroDocumentoOriginal">
                        <tns:numeroDocumentoOriginal>
                           <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:numeroDocumentoOriginal"/>
                        </tns:numeroDocumentoOriginal>
                     </xsl:if>
                     <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:codigoCausal">
                        <tns:codigoCausal>
                           <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:codigoCausal"/>
                        </tns:codigoCausal>
                     </xsl:if>
                     <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:totalNeto">
                        <tns:totalNeto>
                           <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:totalNeto"/>
                        </tns:totalNeto>
                     </xsl:if>
                     <tns:totalBruto>
                        <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:totalBruto"/>
                     </tns:totalBruto>
                     <tns:ventaPersonal>
                        <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:ventaPersonal"/>
                     </tns:ventaPersonal>
                     <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:afectaCuentaCorriente">
                        <tns:afectaCuentaCorriente>
                           <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:afectaCuentaCorriente"/>
                        </tns:afectaCuentaCorriente>
                     </xsl:if>
                     <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:afectaCredito">
                        <tns:afectaCredito>
                           <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:orden/ns0:afectaCredito"/>
                        </tns:afectaCredito>
                     </xsl:if>
                  </tns:orden>
                  <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:promociones">
                     <tns:promociones>
                        <xsl:for-each select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:promociones/ns0:promocion">
                           <tns:promocion>
                              <xsl:if test="ns0:codigoPromocion">
                                 <tns:codigoPromocion>
                                    <xsl:value-of select="ns0:codigoPromocion"/>
                                 </tns:codigoPromocion>
                              </xsl:if>
                              <xsl:if test="ns0:descripcionPromocion">
                                 <tns:descripcionPromocion>
                                    <xsl:value-of select="ns0:descripcionPromocion"/>
                                 </tns:descripcionPromocion>
                              </xsl:if>
                              <tns:descuentoPromocion>
                                 <xsl:value-of select="ns0:descuentoPromocion"/>
                              </tns:descuentoPromocion>
                           </tns:promocion>
                        </xsl:for-each>
                     </tns:promociones>
                  </xsl:if>
                  <tns:datosCliente>
                     <tns:tipoIdCliente>
                        <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente"/>
                     </tns:tipoIdCliente>
                     <tns:idCliente>
                        <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:idCliente"/>
                     </tns:idCliente>
                     <tns:nombre>
                        <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:nombre"/>
                     </tns:nombre>
                     <tns:mail>
                        <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:mail"/>
                     </tns:mail>
                     <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:telefono">
                        <tns:telefono>
                           <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:telefono"/>
                        </tns:telefono>
                     </xsl:if>
                     <tns:paisCliente>
                        <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:paisCliente"/>
                     </tns:paisCliente>
                     <tns:localizacionDatosCliente>
                        <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:localizacionDatosCliente/ns0:arg">
                           <tns:arg>
                              <tns:condicionImpositiva>
                                 <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:localizacionDatosCliente/ns0:arg/ns0:condicionImpositiva"/>
                              </tns:condicionImpositiva>
                           </tns:arg>
                        </xsl:if>
                     </tns:localizacionDatosCliente>
                     <tns:direccion>
                        <tns:nombreCalle>
                           <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:nombreCalle"/>
                        </tns:nombreCalle>
                        <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:codigoPostal">
                           <tns:codigoPostal>
                              <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:codigoPostal"/>
                           </tns:codigoPostal>
                        </xsl:if>
                        <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:subAdmArea">
                           <tns:subAdmArea>
                              <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:subAdmArea"/>
                           </tns:subAdmArea>
                        </xsl:if>
                        <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localidad">
                           <tns:localidad>
                              <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localidad"/>
                           </tns:localidad>
                        </xsl:if>
                        <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:admArea">
                           <tns:admArea>
                              <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:admArea"/>
                           </tns:admArea>
                        </xsl:if>
                        <tns:localizacionDireccionCliente>
                           <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localizacionDireccionCliente/ns0:uru">
                              <tns:uru>
                                 <tns:numeroDepartamento>
                                    <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localizacionDireccionCliente/ns0:uru/ns0:numeroDepartamento"/>
                                 </tns:numeroDepartamento>
                                 <tns:numeroCalle>
                                    <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localizacionDireccionCliente/ns0:uru/ns0:numeroCalle"/>
                                 </tns:numeroCalle>
                              </tns:uru>
                           </xsl:if>
                           <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localizacionDireccionCliente/ns0:arg">
                              <tns:arg>
                                 <tns:numeroDepartamento>
                                    <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localizacionDireccionCliente/ns0:arg/ns0:numeroDepartamento"/>
                                 </tns:numeroDepartamento>
                                 <tns:numeroCalle>
                                    <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localizacionDireccionCliente/ns0:arg/ns0:numeroCalle"/>
                                 </tns:numeroCalle>
                              </tns:arg>
                           </xsl:if>
                        </tns:localizacionDireccionCliente>
                     </tns:direccion>
                  </tns:datosCliente>
                  <tns:localizacionCabecera>
                     <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:localizacionCabecera/ns0:uru">
                        <tns:uru>
                           <tns:tasaVendendorDelDia>
                              <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:localizacionCabecera/ns0:uru/ns0:tasaVendendorDelDia"/>
                           </tns:tasaVendendorDelDia>
                           <tns:tasaCompradorDelDia>
                              <xsl:value-of select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:localizacionCabecera/ns0:uru/ns0:tasaCompradorDelDia"/>
                           </tns:tasaCompradorDelDia>
                        </tns:uru>
                     </xsl:if>
                  </tns:localizacionCabecera>
                  <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosAdicionalesCabecera">
                     <tns:datosAdicionalesCabecera>
                        <xsl:for-each select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:datosAdicionalesCabecera/ns0:datoAdicionalCabecera">
                           <tns:datoAdicionalCabecera>
                              <xsl:if test="ns0:campo">
                                 <tns:campo>
                                    <xsl:value-of select="ns0:campo"/>
                                 </tns:campo>
                              </xsl:if>
                              <xsl:if test="ns0:valor">
                                 <tns:valor>
                                    <xsl:value-of select="ns0:valor"/>
                                 </tns:valor>
                              </xsl:if>
                           </tns:datoAdicionalCabecera>
                        </xsl:for-each>
                     </tns:datosAdicionalesCabecera>
                  </xsl:if>
                  <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:cargosDescuento">
                     <tns:cargosDescuento>
                        <xsl:for-each select="/ns0:ClienteDocumentosEmitirExpReq/ns0:cabecera/ns0:cargosDescuento/ns0:cargoDescuento">
                           <tns:cargoDescuento>
                              <xsl:if test="ns0:tipoCargoDescuento">
                                 <tns:tipoCargoDescuento>
                                    <xsl:value-of select="ns0:tipoCargoDescuento"/>
                                 </tns:tipoCargoDescuento>
                              </xsl:if>
                              <xsl:if test="ns0:codigoCargoDescuento">
                                 <tns:codigoCargoDescuento>
                                    <xsl:value-of select="ns0:codigoCargoDescuento"/>
                                 </tns:codigoCargoDescuento>
                              </xsl:if>
                              <xsl:if test="ns0:descripcionCargoDescuento">
                                 <tns:descripcionCargoDescuento>
                                    <xsl:value-of select="ns0:descripcionCargoDescuento"/>
                                 </tns:descripcionCargoDescuento>
                              </xsl:if>
                              <xsl:if test="ns0:montoCargoDescuento">
                                 <tns:montoCargoDescuento>
                                    <xsl:value-of select="ns0:montoCargoDescuento"/>
                                 </tns:montoCargoDescuento>
                              </xsl:if>
                           </tns:cargoDescuento>
                        </xsl:for-each>
                     </tns:cargosDescuento>
                  </xsl:if>
               </tns:cabecera>
               <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:detalles">
                  <tns:detalles>
                     <xsl:for-each select="/ns0:ClienteDocumentosEmitirExpReq/ns0:detalles/ns0:detalle">
                        <tns:detalle>
                           <tns:numeroLinea>
                              <xsl:value-of select="ns0:numeroLinea"/>
                           </tns:numeroLinea>
                           <tns:codigo>
                              <xsl:value-of select="ns0:codigo"/>
                           </tns:codigo>
                           <tns:cantidadProducto>
                              <xsl:value-of select="ns0:cantidadProducto"/>
                           </tns:cantidadProducto>
                           <tns:precio>
                              <xsl:value-of select="ns0:precio"/>
                           </tns:precio>
                           <xsl:if test="ns0:tipoMoneda">
                              <tns:tipoMoneda>
                                 <xsl:value-of select="ns0:tipoMoneda"/>
                              </tns:tipoMoneda>
                           </xsl:if>
                           <xsl:if test="ns0:descripcion">
                              <tns:descripcion>
                                 <xsl:value-of select="ns0:descripcion"/>
                              </tns:descripcion>
                           </xsl:if>
                           <xsl:if test="ns0:unidadMedida">
                              <tns:unidadMedida>
                                 <xsl:value-of select="ns0:unidadMedida"/>
                              </tns:unidadMedida>
                           </xsl:if>
                           <xsl:if test="ns0:idProveedor">
                              <tns:idProveedor>
                                 <xsl:value-of select="ns0:idProveedor"/>
                              </tns:idProveedor>
                           </xsl:if>
                           <tns:precioSubTotal>
                              <xsl:value-of select="ns0:precioSubTotal"/>
                           </tns:precioSubTotal>
                           <xsl:if test="ns0:promociones">
                              <tns:promociones>
                                 <xsl:for-each select="ns0:promociones/ns0:promocion">
                                    <tns:promocion>
                                       <xsl:if test="ns0:codigoPromocion">
                                          <tns:codigoPromocion>
                                             <xsl:value-of select="ns0:codigoPromocion"/>
                                          </tns:codigoPromocion>
                                       </xsl:if>
                                       <xsl:if test="ns0:descripcionPromocion">
                                          <tns:descripcionPromocion>
                                             <xsl:value-of select="ns0:descripcionPromocion"/>
                                          </tns:descripcionPromocion>
                                       </xsl:if>
                                       <xsl:if test="ns0:descuentoPromocion">
                                          <tns:descuentoPromocion>
                                             <xsl:value-of select="ns0:descuentoPromocion"/>
                                          </tns:descuentoPromocion>
                                       </xsl:if>
                                    </tns:promocion>
                                 </xsl:for-each>
                              </tns:promociones>
                           </xsl:if>
                           <xsl:if test="ns0:localizacionDetalle">
                              <tns:localizacionDetalle>
                                 <xsl:if test="ns0:localizacionDetalle/ns0:uru">
                                    <tns:uru>
                                       <xsl:if test="ns0:localizacionDetalle/ns0:uru/ns0:valorDolar">
                                          <tns:valorDolar>
                                             <xsl:value-of select="ns0:localizacionDetalle/ns0:uru/ns0:valorDolar"/>
                                          </tns:valorDolar>
                                       </xsl:if>
                                    </tns:uru>
                                 </xsl:if>
                              </tns:localizacionDetalle>
                           </xsl:if>
                           <xsl:if test="ns0:datosAdicionalesDetalle">
                              <tns:datosAdicionalesDetalle>
                                 <xsl:for-each select="ns0:datosAdicionalesDetalle/ns0:datoAdicionalDetalle">
                                    <tns:datoAdicionalDetalle>
                                       <xsl:if test="ns0:campo">
                                          <tns:campo>
                                             <xsl:value-of select="ns0:campo"/>
                                          </tns:campo>
                                       </xsl:if>
                                       <xsl:if test="ns0:valor">
                                          <tns:valor>
                                             <xsl:value-of select="ns0:valor"/>
                                          </tns:valor>
                                       </xsl:if>
                                    </tns:datoAdicionalDetalle>
                                 </xsl:for-each>
                              </tns:datosAdicionalesDetalle>
                           </xsl:if>
                        </tns:detalle>
                     </xsl:for-each>
                  </tns:detalles>
               </xsl:if>
               <xsl:if test="/ns0:ClienteDocumentosEmitirExpReq/ns0:formasPago">
                  <tns:formasPago>
                     <xsl:for-each select="/ns0:ClienteDocumentosEmitirExpReq/ns0:formasPago/ns0:formaPago">
                        <tns:formaPago>
                           <tns:tipoFormaPago>
                              <xsl:value-of select="ns0:tipoFormaPago"/>
                           </tns:tipoFormaPago>
                           <xsl:if test="ns0:tipoTarjeta">
                              <tns:tipoTarjeta>
                                 <xsl:value-of select="ns0:tipoTarjeta"/>
                              </tns:tipoTarjeta>
                           </xsl:if>
                           <xsl:if test="ns0:numeroMedioPago">
                              <tns:numeroMedioPago>
                                 <xsl:value-of select="ns0:numeroMedioPago"/>
                              </tns:numeroMedioPago>
                           </xsl:if>
                           <xsl:if test="ns0:numeroUnico">
                              <tns:numeroUnico>
                                 <xsl:value-of select="ns0:numeroUnico"/>
                              </tns:numeroUnico>
                           </xsl:if>
                           <tns:monto>
                              <xsl:value-of select="ns0:monto"/>
                           </tns:monto>
                           <xsl:if test="ns0:numeroCuotas">
                              <tns:numeroCuotas>
                                 <xsl:value-of select="ns0:numeroCuotas"/>
                              </tns:numeroCuotas>
                           </xsl:if>
                           <xsl:if test="ns0:codigoAutorizacion">
                              <tns:codigoAutorizacion>
                                 <xsl:value-of select="ns0:codigoAutorizacion"/>
                              </tns:codigoAutorizacion>
                           </xsl:if>
                           <xsl:if test="ns0:tipoMoneda">
                              <tns:tipoMoneda>
                                 <xsl:value-of select="ns0:tipoMoneda"/>
                              </tns:tipoMoneda>
                           </xsl:if>
                           <xsl:if test="ns0:plazoPago">
                              <tns:plazoPago>
                                 <xsl:value-of select="ns0:plazoPago"/>
                              </tns:plazoPago>
                           </xsl:if>
                           <tns:pasarela>
                              <xsl:value-of select="ns0:pasarela"/>
                           </tns:pasarela>
                           <xsl:if test="ns0:montoCuota">
                              <tns:montoCuota>
                                 <xsl:value-of select="ns0:montoCuota"/>
                              </tns:montoCuota>
                           </xsl:if>
                           <xsl:if test="ns0:codigoComercio">
                              <tns:codigoComercio>
                                 <xsl:value-of select="ns0:codigoComercio"/>
                              </tns:codigoComercio>
                           </xsl:if>
                           <xsl:if test="ns0:tipoCuota">
                              <tns:tipoCuota>
                                 <xsl:value-of select="ns0:tipoCuota"/>
                              </tns:tipoCuota>
                           </xsl:if>
                           <xsl:if test="ns0:tipoIdCliente">
                              <tns:tipoIdCliente>
                                 <xsl:value-of select="ns0:tipoIdCliente"/>
                              </tns:tipoIdCliente>
                           </xsl:if>
                           <xsl:if test="ns0:idCliente">
                              <tns:idCliente>
                                 <xsl:value-of select="ns0:idCliente"/>
                              </tns:idCliente>
                           </xsl:if>
                           <xsl:if test="ns0:localizacionFormaPago">
                              <tns:localizacionFormaPago>
                                 <xsl:if test="ns0:localizacionFormaPago/ns0:arg">
                                    <tns:arg>
                                       <tns:recargoFinanciero>
                                          <xsl:value-of select="ns0:localizacionFormaPago/ns0:arg/ns0:recargoFinanciero"/>
                                       </tns:recargoFinanciero>
                                       <tns:numOperacion>
                                          <xsl:value-of select="ns0:localizacionFormaPago/ns0:arg/ns0:numOperacion"/>
                                       </tns:numOperacion>
                                       <tns:codMarcaTarjeta>
                                          <xsl:value-of select="ns0:localizacionFormaPago/ns0:arg/ns0:codMarcaTarjeta"/>
                                       </tns:codMarcaTarjeta>
                                       <tns:marcaTarjeta>
                                          <xsl:value-of select="ns0:localizacionFormaPago/ns0:arg/ns0:marcaTarjeta"/>
                                       </tns:marcaTarjeta>
                                    </tns:arg>
                                 </xsl:if>
                                 <xsl:if test="ns0:localizacionFormaPago/ns0:uru">
                                    <tns:uru>
                                       <tns:recargoFinanciero>
                                          <xsl:value-of select="ns0:localizacionFormaPago/ns0:uru/ns0:recargoFinanciero"/>
                                       </tns:recargoFinanciero>
                                       <tns:numOperacion>
                                          <xsl:value-of select="ns0:localizacionFormaPago/ns0:uru/ns0:numOperacion"/>
                                       </tns:numOperacion>
                                       <tns:codMarcaTarjeta>
                                          <xsl:value-of select="ns0:localizacionFormaPago/ns0:uru/ns0:codMarcaTarjeta"/>
                                       </tns:codMarcaTarjeta>
                                       <tns:marcaTarjeta>
                                          <xsl:value-of select="ns0:localizacionFormaPago/ns0:uru/ns0:marcaTarjeta"/>
                                       </tns:marcaTarjeta>
                                    </tns:uru>
                                 </xsl:if>
                              </tns:localizacionFormaPago>
                           </xsl:if>
                           <xsl:if test="ns0:datosAdicionalesFormaPago">
                              <tns:datosAdicionalesFormaPago>
                                 <xsl:for-each select="ns0:datosAdicionalesFormaPago/ns0:datoAdicionalFormaPago">
                                    <tns:datoAdicionalFormaPago>
                                       <xsl:if test="ns0:campo">
                                          <tns:campo>
                                             <xsl:value-of select="ns0:campo"/>
                                          </tns:campo>
                                       </xsl:if>
                                       <xsl:if test="ns0:valor">
                                          <tns:valor>
                                             <xsl:value-of select="ns0:valor"/>
                                          </tns:valor>
                                       </xsl:if>
                                    </tns:datoAdicionalFormaPago>
                                 </xsl:for-each>
                              </tns:datosAdicionalesFormaPago>
                           </xsl:if>
                        </tns:formaPago>
                     </xsl:for-each>
                  </tns:formasPago>
               </xsl:if>
            </tns:ClienteDocumentosEmitirProdReq>
         </tns:BodyProducer>
      </tns:ClienteDocumentosEmitirRequest>
   </xsl:template>
</xsl:stylesheet>
