<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://mdwcorp.falabella.com/SOD/CORP/WLS/schema/Uxpos/Cliente/Documentos/Emitir/Request/v2018.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 oraxsl">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="xsd/SOD_CORP_Uxpos_Cliente_Documentos_Emitir_Req.xsd"/>
            <oracle-xsl-mapper:rootElement name="ClienteDocumentosEmitirRequest" namespace="http://mdwcorp.falabella.com/SOD/CORP/WLS/schema/Uxpos/Cliente/Documentos/Emitir/Request/v2018.02"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="UxposSchema.xsd"/>
            <oracle-xsl-mapper:rootElement name="VSS" namespace=""/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [WED FEB 14 10:37:38 CLT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <VSS>
         <T>
            <Cabecera>
               <Orden NroOrden="{concat(/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:sucursal,
               /ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:ordenVenta)}"
                      ImporteTotalOrden="{translate(format-number (/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:totalBruto, '#0.00' ),'.','')}"
                      VentaEmpleado="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:ventaPersonal}">
                  <xsl:attribute name="TipoComprobante">
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:tipoDocumentoVenta/text() = 4">
        
                     <xsl:text>TIC</xsl:text>
                    </xsl:if>              
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:tipoDocumentoVenta/text() = 5">
                    
                     <xsl:text>TIB</xsl:text>
                    </xsl:if>
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:tipoDocumentoVenta/text() = 6">
                     
                      <xsl:text>TIA</xsl:text>
                    </xsl:if>
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:tipoDocumentoVenta/text() = 7">
                     
                     <xsl:text>FAB</xsl:text>
                    </xsl:if>
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:tipoDocumentoVenta/text() = 8">
                    
                     <xsl:text>FAA</xsl:text>
                    </xsl:if>
                  </xsl:attribute>
               </Orden>
               <Cliente
                        NroDocumentoCliente="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:idCliente}"
                        Nombre="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:nombre}"
                        Email="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:mail}"
                        Telefono="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:telefono}"
                        CondImpositiva="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:localizacionDatosCliente/ns0:arg/ns0:condicionImpositiva}"
                        DirCalle="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:nombreCalle}"
                        DirCodPostal="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:codigoPostal}"
                        DirProvincia="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:admArea}"
                        DirDepartamento="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localidad}"
                        DirLocalidad="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:subAdmArea}"
                        DirPiso="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localizacionDireccionCliente/ns0:arg/ns0:numeroDepartamento}"
                        DirNro="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localizacionDireccionCliente/ns0:arg/ns0:numeroCalle}">
                  <xsl:attribute name="TipDocCliente">
                  
                     <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 5" >
                       <xsl:text>T</xsl:text>
                    </xsl:if>
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 3">
                     
                       <xsl:text>D</xsl:text>
                    </xsl:if>
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 2">
                       
                       <xsl:text>C</xsl:text>
                    </xsl:if>
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 6">
                    
                       <xsl:text>P</xsl:text>
                    </xsl:if>
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 7">
                   
                       <xsl:text>L</xsl:text>
                    </xsl:if>
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 8">
                      
                       <xsl:text>E</xsl:text>
                    </xsl:if>
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 9">
                     
                       <xsl:text>U</xsl:text>
                    </xsl:if>
                  </xsl:attribute>
               </Cliente>
            </Cabecera>
            <Detalles>
            <xsl:for-each select="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:detalles/ns0:detalle">
               <Detalle numeroLinea="{ns0:numeroLinea}"
                        SKU="{ns0:codigo}"
                        Cantidad="{ns0:cantidadProducto}"
                        PrecioUnitario="{translate(format-number (ns0:precio, '#0.00' ),'.','')}"
                        Descripcion="{ns0:descripcion}"
                        PrecioSubtotal="{translate(format-number (ns0:precioSubTotal, '#0.00' ),'.','')}"
                        DescuentoPromocion="{translate(format-number (ns0:promociones/ns0:promocion/ns0:descuentoPromocion, '#0.00' ),'.','')}">
                     <xsl:attribute name="tipoMoneda">
                         <xsl:if test="ns0:tipoMoneda/text() = 1">
                        
                           <xsl:text>CLP</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoMoneda/text() = 2">
                           
                           <xsl:text>ARS</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoMoneda/text() = 3">
                          
                           <xsl:text>PEN</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoMoneda/text() = 4">
                         
                           <xsl:text>UYU</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoMoneda/text() = 5">
                       
                           <xsl:text>USD</xsl:text>
                        </xsl:if>
                     </xsl:attribute>
                  </Detalle>
			   </xsl:for-each> 
            </Detalles>
            <FormasPago>
                 <xsl:for-each select="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:formasPago/ns0:formaPago">
               <FormaPago
                          TipoTarjeta="{ns0:tipoTarjeta}"
                          NumTarjeta="{ns0:numeroMedioPago}"
                          numeroUnico="{ns0:numeroUnico}"
                          ImportePago="{translate(format-number (ns0:monto, '#0.00' ),'.','')}"
                          NroCuotas="{ns0:numeroCuotas}"
                          CodAutorizacion="{ns0:codigoAutorizacion}"
                          ImporteCuotas="{translate(format-number (ns0:montoCuota, '#0.00' ),'.','')}"
                          Pasarela="{ns0:pasarela}"
                          codComercio="{ns0:codigoComercio}"
                          TipoCuota="{ns0:tipoCuota}"
                          NroDocumentoTitular="{ns0:idCliente}"
                          ImporteRecargoFinanciero="{translate(format-number (ns0:localizacionFormaPago/ns0:arg/ns0:recargoFinanciero, '#0.00' ),'.','')}"
                          NumeroOperacion="{ns0:localizacionFormaPago/ns0:arg/ns0:numOperacion}"
                          CodMarcaTarjeta="{ns0:localizacionFormaPago/ns0:arg/ns0:codMarcaTarjeta}"
                          MarcaTarjeta="{ns0:localizacionFormaPago/ns0:arg/ns0:marcaTarjeta}">
                     <xsl:attribute name="TipDocTitular">
                        <xsl:if test="ns0:tipoIdCliente/text() = 5">
                           
                           <xsl:text>T</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoIdCliente/text() = 3">
                       
                           <xsl:text>D</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoIdCliente/text() = 2">
                        
                           <xsl:text>C</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoIdCliente/text() = 6">
               
                           <xsl:text>P</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoIdCliente/text() = 7">
                         
                           <xsl:text>L</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoIdCliente/text() = 8">
                        
                           <xsl:text>E</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoIdCliente/text() = 9">
                 
                           <xsl:text>U</xsl:text>
                        </xsl:if>
                     </xsl:attribute>
                     
                     
                     <xsl:attribute name="tipoMoneda">
                        <xsl:if test="ns0:tipoMoneda/text() = 1">
                  
                           <xsl:text>CLP</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoMoneda/text() = 2">
                         
                           <xsl:text>ARS</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoMoneda/text() = 3">
                    
                           <xsl:text>PEN</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoMoneda/text() = 4">
                          
                           <xsl:text>UYU</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoMoneda/text() = 5">
                         
                           <xsl:text>USD</xsl:text>
                        </xsl:if>
                     </xsl:attribute>
                     
                     <xsl:attribute name="CodMedioPago">
                        <xsl:if test="ns0:tipoFormaPago/text() = 1">
                         
                           <xsl:text>TF</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoFormaPago/text() = 2">
                 
                           <xsl:text>PW</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoFormaPago/text() = 3">
                      
                           <xsl:text>TV</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoFormaPago/text() = 4">
                      
                           <xsl:text>DB</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoFormaPago/text() = 5">
                        
                           <xsl:text>TE</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoFormaPago/text() = 6">
                          
                           <xsl:text>A1</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoFormaPago/text() = 9">
                       
                           <xsl:text>GC</xsl:text>
                        </xsl:if>
                        <xsl:if test="ns0:tipoFormaPago/text() = 10">
                   
                           <xsl:text>NC</xsl:text>
                        </xsl:if>
                     </xsl:attribute>
                  </FormaPago>
                </xsl:for-each> 
            </FormasPago>
            
         </T>
      </VSS>
   </xsl:template>
</xsl:stylesheet>
