<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns1="http://mdwcorp.falabella.com/SOD/CORP/WLS/schema/Uxpos/Cliente/Documentos/Emitir/Request/v2018.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns1 oraxsl">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="xsd/WLS_SOD_AR_Uxpos_Documentos_Emitir.xsd"/>
            <oracle-xsl-mapper:rootElement name="ClienteDocumentosEmitirRequest" namespace="http://mdwcorp.falabella.com/SOD/CORP/WLS/schema/Uxpos/Cliente/Documentos/Emitir/Request/v2018.02"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="WLS_SOD_UY_Uxpos_Documentos_Emitir.xsd"/>
            <oracle-xsl-mapper:rootElement name="VSS" namespace=""/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON FEB 19 00:42:29 CLST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <VSS>
         <T>
            <Cabecera>
               <Orden NroOrden="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:orden/ns1:ordenVenta}"
                      ImporteTotalOrden="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:orden/ns1:totalBruto}"
                      VentaEmpleado="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:orden/ns1:ventaPersonal}">
                  <xsl:attribute name="TipoComprobante">
                  <xsl:if test="/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:orden/ns1:tipoDocumentoVenta/text() = 1">
                   
					 <xsl:text>BLT</xsl:text>
                  </xsl:if>
                  <xsl:if test="/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:orden/ns1:tipoDocumentoVenta/text() = 2">
                    
					 <xsl:text>FME</xsl:text>
                  </xsl:if>
                  </xsl:attribute>
               </Orden>
               <Cliente
                        Nombre="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:nombre}"
                        Email="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:mail}"
                        Telefono="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:telefono}"
                        paiscli="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:paisCliente}"
                        DirCalle="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:direccion/ns1:nombreCalle}"
                        DirCodPostal="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:direccion/ns1:codigoPostal}"
                        DirLocalidad="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:direccion/ns1:subAdmArea}"
                        DirDepartamento="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:direccion/ns1:localidad}"
                        DirProvincia="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:direccion/ns1:admArea}"
                        DirPiso="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:direccion/ns1:localizacionDireccionCliente/ns1:uru/ns1:numeroDepartamento}"
                        DirNro="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:direccion/ns1:localizacionDireccionCliente/ns1:uru/ns1:numeroCalle}"
                        TasaVendedor="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:localizacionCabecera/ns1:uru/ns1:tasaVendendorDelDia}"
                        TasaComprador="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:localizacionCabecera/ns1:uru/ns1:tasaCompradorDelDia}"
                        NroDocumentoCliente="{/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:idCliente}">
                  <xsl:attribute name="TipDocCliente">
                  <xsl:if test="/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:tipoIdCliente/text() = 1">
                    
					 <xsl:text>R</xsl:text>
                  </xsl:if>
                  <xsl:if test="/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:tipoIdCliente/text() = 2">
                    
					 <xsl:text>C</xsl:text>
                  </xsl:if>
                  <xsl:if test="/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:tipoIdCliente/text() = 3">
                    
					 <xsl:text>D</xsl:text>
                  </xsl:if> 
                   <xsl:if test="/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:tipoIdCliente/text() = 6">
                     
					 <xsl:text>P</xsl:text>
                  </xsl:if>
                   <xsl:if test="/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:cabecera/ns1:datosCliente/ns1:tipoIdCliente/text() = 12">
                     
					 <xsl:text>O</xsl:text>
                  </xsl:if>
                  </xsl:attribute>
               </Cliente>
            </Cabecera>
            <Detalles>
                <xsl:for-each select="/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:detalles/ns1:detalle">
       
               <Detalle numeroLinea="{ns1:numeroLinea}"
                        SKU="{ns1:codigo}"
                        Cantidad="{ns1:cantidadProducto}"
                        PrecioUnitario="{ns1:precio}"
                        Descripcion="{ns1:descripcion}"
                        PrecioSubtotal="{ns1:precioSubTotal}"
                        DescuentoPromocion="{ns1:promociones/ns1:promocion/ns1:descuentoPromocion}"
                        ValorDolar="{ns1:localizacionDetalle/ns1:uru/ns1:valorDolar}">
                     <xsl:attribute name="tipoMoneda">
                      <xsl:if test="ns1:tipoMoneda/text() = 1 ">
                    
						<xsl:text>CLP</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns1:tipoMoneda/text() = 2 ">
                   
						<xsl:text>ARS</xsl:text>
                    </xsl:if>
                    <xsl:if test="ns1:tipoMoneda/text() = 3 ">
                  
						<xsl:text>PEN</xsl:text>
                    </xsl:if>   
                    <xsl:if test="ns1:tipoMoneda/text() = 4 ">
                    
						<xsl:text>UYU</xsl:text>
                    </xsl:if>   
                    <xsl:if test="ns1:tipoMoneda/text() = 5 ">
                       
						<xsl:text>USD</xsl:text>
                    </xsl:if>   
                    
                     </xsl:attribute>
                  </Detalle>
            </xsl:for-each>
            </Detalles>
            <FormasPago>
                    <xsl:for-each select="/ns1:ClienteDocumentosEmitirRequest/ns1:BodyProducer/ns1:ClienteDocumentosEmitirProdReq/ns1:formasPago/ns1:formaPago">
        
               <FormaPago
                          TipoTarjeta="{ns1:tipoTarjeta}"
                          NumTarjeta="{ns1:numeroMedioPago}"
                          numeroUnico="{ns1:numeroUnico}"
                          ImportePago="{ns1:monto}"
                          NroCuotas="{ns1:numeroCuotas}"
                          CodAutorizacion="{ns1:codigoAutorizacion}"
                          Pasarela="{ns1:pasarela}"
                          ImporteCuotas="{ns1:montoCuota}"
                          CodigoComercio="{ns1:codigoComercio}"
                          TipoCuota="{ns1:tipoCuota}"
                          NroDocumentoTitular="{ns1:idCliente}"
                          ImporteRecargoFinanciero="{ns1:localizacionFormaPago/ns1:uru/ns1:recargoFinanciero}"
                          NumeroOperacion="{ns1:localizacionFormaPago/ns1:uru/ns1:numOperacion}"
                          CodMarcaTarjeta="{ns1:localizacionFormaPago/ns1:uru/ns1:codMarcaTarjeta}"
                          MarcaTarjeta="{ns1:localizacionFormaPago/ns1:uru/ns1:marcaTarjeta}">
                     <xsl:attribute name="TipDocTitular">
                     <xsl:if test="ns1:tipoIdCliente/text() = 1 ">
                   
						<xsl:text>R</xsl:text>
                    </xsl:if>
                    <xsl:if test="ns1:tipoIdCliente/text() = 2 ">
                    
						<xsl:text>C</xsl:text>
                    </xsl:if>
                    <xsl:if test="ns1:tipoIdCliente/text() = 3 ">
                 
						<xsl:text>D</xsl:text>
                    </xsl:if>
                    <xsl:if test="ns1:tipoIdCliente/text() = 6 ">
                       
						<xsl:text>P</xsl:text>
                    </xsl:if>
                    <xsl:if test="ns1:tipoIdCliente/text() = 12 ">
                       
						<xsl:text>O</xsl:text>
                    </xsl:if>
                     </xsl:attribute>
                     
                     <xsl:attribute name="tipoMoneda">
                     <xsl:if test="ns1:tipoMoneda/text() = 1 ">
                       
						<xsl:text>CLP</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns1:tipoMoneda/text() = 2 ">
                       
						<xsl:text>ARS</xsl:text>
                    </xsl:if>
                    <xsl:if test="ns1:tipoMoneda/text() = 3 ">
                        
						<xsl:text>PEN</xsl:text>
                    </xsl:if>   
                    <xsl:if test="ns1:tipoMoneda/text() = 4 ">
                       
						<xsl:text>UYU</xsl:text>
                    </xsl:if>   
                    <xsl:if test="ns1:tipoMoneda/text() = 5 ">
                        
						<xsl:text>USD</xsl:text>
                    </xsl:if>   
            
                     </xsl:attribute>
                     
                     <xsl:attribute name="CodMedioPago">
                      <xsl:if test="ns1:tipoFormaPago/text() = 1 ">
                  
						<xsl:text>TF</xsl:text>
                    </xsl:if>
                      <xsl:if test="ns1:tipoFormaPago/text() = 2 ">
                      
						<xsl:text>PW</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns1:tipoFormaPago/text() = 3 ">
                    
						<xsl:text>TV</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns1:tipoFormaPago/text() = 4 ">
                     
						<xsl:text>DB</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns1:tipoFormaPago/text() = 5 ">
                     
						<xsl:text>TE</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns1:tipoFormaPago/text() = 6 ">
                    
						<xsl:text>A1</xsl:text>
                    </xsl:if>
                    <xsl:if test="ns1:tipoFormaPago/text() = 7 ">
                       
						<xsl:text>DC</xsl:text>
                    </xsl:if>
                    <xsl:if test="ns1:tipoFormaPago/text() = 8 ">
                     
						<xsl:text>DD</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns1:tipoFormaPago/text() = 9 ">
                        
						<xsl:text>GC</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns1:tipoFormaPago/text() = 10 ">
                        
						<xsl:text>NC</xsl:text>
                    </xsl:if>
                
                     </xsl:attribute>
                  </FormaPago>
            </xsl:for-each>
            </FormasPago>
         </T>
      </VSS>
   </xsl:template>
</xsl:stylesheet>
