<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://mdwcorp.falabella.com/SOD/CORP/WLS/schema/Uxpos/Cliente/Documentos/Emitir/Request/v2018.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 oraxsl">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="xsd/WLS_SOD_PE_Uxpos_Documentos_Emitir.xsd"/>
            <oracle-xsl-mapper:rootElement name="ClienteDocumentosEmitirRequest" namespace="http://mdwcorp.falabella.com/SOD/CORP/WLS/schema/Uxpos/Cliente/Documentos/Emitir/Request/v2018.02"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="xsd/UXPOS_Schema.xsd"/>
            <oracle-xsl-mapper:rootElement name="VSS" namespace=""/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [WED FEB 21 15:41:04 CLST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <VSS>
         <T>
            <Cabecera NroOrden="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:ordenVenta}"
                      ImporteTotalOrden="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:totalBruto}"
                      ventapersonal="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:ventaPersonal}"
                      id="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:idCliente}"
                      nombreCli="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:nombre}"
                      mail1="{substring-before(/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:mail,'@')}"
                      mail2="{substring-after(/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:mail,'@')}"
                      fonocli="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:telefono}"
                      paiscli="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:paisCliente}"
                      direccioncli="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:nombreCalle}"
                      DirCodPostal="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:codigoPostal}"
                      comunacli="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:subAdmArea}"
                      ciudadcli="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:localidad}"
                      regioncli="{/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:direccion/ns0:admArea}">
               <xsl:attribute name="tipoId">
                 <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 3 ">
                        
						<xsl:text>D</xsl:text>
                    </xsl:if>
                 
                 <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 4 ">
                        
						<xsl:text>R</xsl:text>
                    </xsl:if>
                 <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 6 ">
                        
						<xsl:text>P</xsl:text>
                    </xsl:if>
                 <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 10 ">
                        
						<xsl:text>E</xsl:text>
                    </xsl:if>
                 <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:datosCliente/ns0:tipoIdCliente/text() = 11 ">
                        
						<xsl:text>A</xsl:text>
                    </xsl:if>

               </xsl:attribute>
               <xsl:attribute name="tipoDoc">
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:tipoDocumentoVenta/text() = 1 ">
                       
						<xsl:text>BLT</xsl:text>
                    </xsl:if>
                    <xsl:if test="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:cabecera/ns0:orden/ns0:tipoDocumentoVenta/text() = 2 ">
                  
						<xsl:text>FAC</xsl:text>
                    </xsl:if>
               </xsl:attribute>
            </Cabecera>
            <Detalles>
              <xsl:for-each select="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:detalles/ns0:detalle">
         
               <Detalle numeroLinea="{ns0:numeroLinea}"
                        codigo="{ns0:codigo}"
                        Qty="{ns0:cantidadProducto}"
                        precio="{ns0:precio}"
                        Descripcion="{ns0:descripcion}"
                        monto="{ns0:precioSubTotal}"
                        DescuentoPromocion="{ns0:promociones/ns0:promocion/ns0:descuentoPromocion}">
                     <xsl:attribute name="tipoMoneda">
                     <xsl:if test="ns0:tipoMoneda/text() = 1 ">
                        
						<xsl:text>CLP</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns0:tipoMoneda/text() = 2 ">
                   
						<xsl:text>ARS</xsl:text>
                    </xsl:if>
                    <xsl:if test="ns0:tipoMoneda/text() = 3 ">
                      
						<xsl:text>PEN</xsl:text>
                    </xsl:if>   
                    <xsl:if test="ns0:tipoMoneda/text() = 4 ">
                   
						<xsl:text>UYU</xsl:text>
                    </xsl:if>   
                    <xsl:if test="ns0:tipoMoneda/text() = 5 ">
                       
						<xsl:text>USD</xsl:text>
                    </xsl:if>   
                     </xsl:attribute>
                  </Detalle>
            </xsl:for-each>
            </Detalles>
            <FormasPago>
               <xsl:for-each select="/ns0:ClienteDocumentosEmitirRequest/ns0:BodyProducer/ns0:ClienteDocumentosEmitirProdReq/ns0:formasPago/ns0:formaPago">
           
               <FormaPago
                          tipoTarjeta="{ns0:tipoTarjeta}"
                          numeroTarj="{ns0:numeroMedioPago}"
                          numeroUnico="{ns0:numeroUnico}"
                          Monto="{ns0:monto}"
                          nroCuotas="{ns0:numeroCuotas}"
                          codAutorizacion="{ns0:codigoAutorizacion}"
                          Pasarela="{ns0:pasarela}"
                          montoCuota="{ns0:montoCuota}"
                          codComercio="{ns0:codigoComercio}"
                          diferido="{ns0:tipoCuota}">
                     <xsl:attribute name="tipoMoneda">
                      <xsl:if test="ns0:tipoMoneda/text() = 1 ">
                        
						<xsl:text>CLP</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns0:tipoMoneda/text() = 2 ">
                       
						<xsl:text>ARS</xsl:text>
                    </xsl:if>
                    <xsl:if test="ns0:tipoMoneda/text() = 3 ">
                       
						<xsl:text>PEN</xsl:text>
                    </xsl:if>   
                    <xsl:if test="ns0:tipoMoneda/text() = 4 ">
                        
						<xsl:text>UYU</xsl:text>
                    </xsl:if>   
                    <xsl:if test="ns0:tipoMoneda/text() = 5 ">
                       
						<xsl:text>USD</xsl:text>
                    </xsl:if>   
                     
                     </xsl:attribute>
                     
                     <xsl:attribute name="tipoPago">
                     <xsl:if test="ns0:tipoFormaPago/text() = 1 ">
                        
						<xsl:text>TF</xsl:text>
                    </xsl:if>
                      <xsl:if test="ns0:tipoFormaPago/text() = 2 ">
                      
						<xsl:text>PW</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns0:tipoFormaPago/text() = 3 ">
                      
						<xsl:text>TV</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns0:tipoFormaPago/text() = 4 ">
                      
						<xsl:text>DB</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns0:tipoFormaPago/text() = 5 ">
                       
						<xsl:text>TE</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns0:tipoFormaPago/text() = 6 ">
                        
						<xsl:text>A1</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns0:tipoFormaPago/text() = 9 ">
                       
						<xsl:text>GC</xsl:text>
                    </xsl:if>
                     <xsl:if test="ns0:tipoFormaPago/text() = 10 ">
                       
						<xsl:text>NC</xsl:text>
                    </xsl:if>
                     </xsl:attribute>
                  </FormaPago>
           </xsl:for-each>
            </FormasPago>
         </T>
      </VSS>
   </xsl:template>
</xsl:stylesheet>
